export const RESUME_BUILDER_FLAGS = {
  MASTER: 'CONTENT_RESUME_ENABLED',
  AI_ENABLED: 'CONTENT_RESUME_AI_ENABLED',
  EXPORT_ENABLED: 'CONTENT_RESUME_EXPORT_ENABLED',
  TEMPLATES_ENABLED: 'CONTENT_RESUME_TEMPLATES_ENABLED',
} as const;
