/**
 * Universe Template Engine
 * Generates manifests, workflows, tools, APIs, and UI entrypoints
 * Phase Ω-II
 */

export function createManifestTemplate(id: string) {
  const displayName = id
    .replace(/_/g, " ")
    .replace(/\b\w/g, c => c.toUpperCase());
  
  return {
    id,
    name: `${displayName} Universe`,
    description: `Auto-generated ${displayName} universe. Customize this description.`,
    version: "1.0.0",
    features: [
      "ai_generation",
      "portfolio_tracking",
      "analytics"
    ],
    workflows: [],
    api: [],
    ui: [],
    credits: {
      SUMMARY: 30,
      INSIGHTS: 50,
      ANALYSIS: 75
    }
  };
}

export function createDefaultWorkflows(id: string) {
  return [
    {
      name: `${id}_summary`,
      description: "Generate summary for items"
    },
    {
      name: `${id}_insights`,
      description: "Generate AI insights"
    },
    {
      name: `${id}_analysis`,
      description: "Perform detailed analysis"
    }
  ];
}

export function createAPIStubs(id: string) {
  return [
    "create",
    "update",
    "search",
    "analyze"
  ];
}

export function createUIPages(id: string) {
  return [
    "dashboard",
    "list",
    "detail"
  ];
}

export function createWorkflowFile(id: string, workflowName: string, description: string) {
  return `/**
 * ${description}
 * Universe: ${id}
 * Auto-generated by Phase Ω-II
 */

import type { WorkflowDefinition } from '../schema';

export const ${workflowName.replace(/-/g, '_')}Workflow: WorkflowDefinition = {
  name: '${workflowName}',
  description: '${description}',
  version: 1,
  steps: [
    {
      id: 'generate',
      name: 'Generate Content',
      provider: 'anthropic',
      model: 'claude-3-5-sonnet-20241022',
      action: 'generate',
      input: {
        prompt: 'Customize this prompt for ${id}',
        maxTokens: 500,
      },
    },
  ],
  settings: {
    maxTotalCost: 0.50,
    timeout: 60000,
    enableCaching: false,
  },
};
`;
}

export function createUIEntrypoint(id: string) {
  const componentName = id
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  
  return `'use client';

export default function ${componentName}UniversePage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">${id.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase())} Universe</h1>
      
      <div className="bg-white rounded-lg shadow p-6 mb-6">
        <p className="text-gray-600 mb-4">
          This universe was auto-generated by Phase Ω-II.
        </p>
        <p className="text-sm text-gray-500">
          Customize this page in: app/(communities)/communities/[id]/${id}/page.tsx
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white rounded-lg shadow p-4">
          <h2 className="font-semibold mb-2">Dashboard</h2>
          <p className="text-sm text-gray-600">View your portfolio</p>
        </div>
        <div className="bg-white rounded-lg shadow p-4">
          <h2 className="font-semibold mb-2">Add Item</h2>
          <p className="text-sm text-gray-600">Create new entry</p>
        </div>
        <div className="bg-white rounded-lg shadow p-4">
          <h2 className="font-semibold mb-2">Analytics</h2>
          <p className="text-sm text-gray-600">View insights</p>
        </div>
      </div>
    </div>
  );
}
`;
}

export function createAPIRoute(id: string, endpoint: string) {
  return `import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // TODO: Implement ${endpoint} logic for ${id} universe
    
    return NextResponse.json({
      success: true,
      message: "${endpoint} endpoint for ${id}",
      data: body
    });
  } catch (error) {
    return NextResponse.json(
      { error: String(error) },
      { status: 500 }
    );
  }
}
`;
}
