export const SOCIAL_POSTS_FLAGS = {
  MASTER: 'CONTENT_SOCIAL_ENABLED',
  AI_ENABLED: 'CONTENT_SOCIAL_AI_ENABLED',
  EXPORT_ENABLED: 'CONTENT_SOCIAL_EXPORT_ENABLED',
  TEMPLATES_ENABLED: 'CONTENT_SOCIAL_TEMPLATES_ENABLED',
} as const;
