export const COVER_LETTER_FLAGS = {
  MASTER: 'CONTENT_COVER_LETTER_ENABLED',
  AI_ENABLED: 'CONTENT_COVER_LETTER_AI_ENABLED',
  EXPORT_ENABLED: 'CONTENT_COVER_LETTER_EXPORT_ENABLED',
  TEMPLATES_ENABLED: 'CONTENT_COVER_LETTER_TEMPLATES_ENABLED',
} as const;
