export const EBOOK_CREATOR_FLAGS = {
  MASTER: 'CONTENT_EBOOK_ENABLED',
  AI_ENABLED: 'CONTENT_EBOOK_AI_ENABLED',
  EXPORT_ENABLED: 'CONTENT_EBOOK_EXPORT_ENABLED',
  TEMPLATES_ENABLED: 'CONTENT_EBOOK_TEMPLATES_ENABLED',
} as const;
