export const PRESENTATION_MAKER_FLAGS = {
  MASTER: 'CONTENT_PRESENTATION_ENABLED',
  AI_ENABLED: 'CONTENT_PRESENTATION_AI_ENABLED',
  EXPORT_ENABLED: 'CONTENT_PRESENTATION_EXPORT_ENABLED',
  TEMPLATES_ENABLED: 'CONTENT_PRESENTATION_TEMPLATES_ENABLED',
} as const;
