export const EMAIL_TEMPLATES_FLAGS = {
  MASTER: 'CONTENT_EMAIL_ENABLED',
  AI_ENABLED: 'CONTENT_EMAIL_AI_ENABLED',
  EXPORT_ENABLED: 'CONTENT_EMAIL_EXPORT_ENABLED',
  TEMPLATES_ENABLED: 'CONTENT_EMAIL_TEMPLATES_ENABLED',
} as const;
