/**
 * Collections Universe Feature Flags
 * Phase II: Debt Operations Controls
 */

export const COLLECTIONS_FLAGS = {
  COLLECTIONS_UNIVERSE_ENABLED: process.env.NEXT_PUBLIC_COLLECTIONS_UNIVERSE_ENABLED === 'true',
  COLLECTIONS_OUTREACH_ENABLED: process.env.NEXT_PUBLIC_COLLECTIONS_OUTREACH_ENABLED === 'true',
  COLLECTIONS_SEGMENTATION_ENABLED: process.env.NEXT_PUBLIC_COLLECTIONS_SEGMENTATION_ENABLED === 'true',
  COLLECTIONS_DASHBOARDS_ENABLED: process.env.NEXT_PUBLIC_COLLECTIONS_DASHBOARDS_ENABLED === 'true',
  COLLECTIONS_CLIENT_REPORTS_ENABLED: process.env.NEXT_PUBLIC_COLLECTIONS_CLIENT_REPORTS_ENABLED === 'true',
  COLLECTIONS_PAYMENT_PLANS_ENABLED: process.env.NEXT_PUBLIC_COLLECTIONS_PAYMENT_PLANS_ENABLED === 'true',
} as const;

export function isCollectionsEnabled(): boolean {
  return COLLECTIONS_FLAGS.COLLECTIONS_UNIVERSE_ENABLED;
}

export function isOutreachEnabled(): boolean {
  return COLLECTIONS_FLAGS.COLLECTIONS_UNIVERSE_ENABLED && COLLECTIONS_FLAGS.COLLECTIONS_OUTREACH_ENABLED;
}

export function isSegmentationEnabled(): boolean {
  return COLLECTIONS_FLAGS.COLLECTIONS_UNIVERSE_ENABLED && COLLECTIONS_FLAGS.COLLECTIONS_SEGMENTATION_ENABLED;
}
